[package]
name = "ramble"
version = "0.6.21"
edition = "2024"

[dependencies]
asefile = "0.3.8"
macroquad = "0.4.14"
image = "0.24.9"
hashmap_macro = "0.1.0"
struct_iterable = "0.1.1"
enum-iterator = "2.1.0"
